import type { CurriculumPhase, PortfolioProject, SkillCategory } from '@/lib/types'

export const CURRICULUM: CurriculumPhase[] = [
  {
    phase: 1,
    title: 'Engineering Foundations',
    goal: 'Build scripting and tooling baseline',
    weeks: 'Weeks 1–4',
    topics: [
      {
        key: 'phase1_python_basics',
        title: 'Python for Security',
        description: 'Files, requests, JSON, subprocess, argparse, error handling, logging',
        tools: ['Python', 'pip', 'venv'],
        whyItMatters: 'Python is the lingua franca of security automation. Every detection, scanner, and integration you write will use it. Without this, you cannot automate anything.',
        resources: [
          {
            title: 'Automate the Boring Stuff with Python',
            url: 'https://automatetheboringstuff.com',
            type: 'book',
            isFree: true,
            priority: 'must',
            note: 'Free online book. Chapters 1–9 cover everything you need for security scripting.',
          },
          {
            title: 'Python for Security Professionals – TCM Security',
            url: 'https://academy.tcm-sec.com/p/python-101-for-hackers',
            type: 'course',
            isFree: false,
            priority: 'must',
            note: 'Best security-focused Python course. Teaches exactly the patterns you will use on the job.',
          },
          {
            title: 'Real Python – File I/O, subprocess, argparse',
            url: 'https://realpython.com/read-write-files-python/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Deep-dive articles on the specific modules used in security tooling.',
          },
          {
            title: 'Python Requests Library Docs',
            url: 'https://requests.readthedocs.io/en/latest/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Official docs for HTTP requests in Python — used in every API integration.',
          },
          {
            title: 'TryHackMe – Python Basics',
            url: 'https://tryhackme.com/module/scripting-for-pentesters',
            type: 'practice',
            isFree: false,
            priority: 'optional',
            note: 'Hands-on rooms if you want guided exercises with immediate feedback.',
          },
        ],
      },
      {
        key: 'phase1_bash',
        title: 'Bash Fundamentals',
        description: 'Loops, conditionals, grep/awk/sed, cron, pipes, find',
        tools: ['bash', 'grep', 'awk', 'sed', 'cron'],
        whyItMatters: 'Bash is everywhere in Linux environments. Every cloud instance, CI runner, and security tool uses shell scripts. You need to read, write, and debug them fluently.',
        resources: [
          {
            title: 'The Linux Command Line – William Shotts (free PDF)',
            url: 'https://linuxcommand.org/tlcl.php',
            type: 'book',
            isFree: true,
            priority: 'must',
            note: 'The definitive free book. Read Part 4 (Writing Shell Scripts) first.',
          },
          {
            title: 'OverTheWire: Bandit',
            url: 'https://overthewire.org/wargames/bandit/',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Wargame that teaches Linux/Bash by forcing you to solve progressively harder challenges. Level 0–20 covers everything in this topic.',
          },
          {
            title: "Ryan's Bash Scripting Tutorial",
            url: 'https://ryanstutorials.net/bash-scripting-tutorial/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Concise, practical scripting guide. Good reference to bookmark.',
          },
          {
            title: 'Greg\'s Bash Guide',
            url: 'https://mywiki.wooledge.org/BashGuide',
            type: 'article',
            isFree: true,
            priority: 'optional',
            note: 'Deep-dive into bash idioms. Useful when you hit confusing behavior.',
          },
        ],
      },
      {
        key: 'phase1_git',
        title: 'Git / GitHub',
        description: 'Branches, commits, PRs, hooks, GitHub Actions basics',
        tools: ['git', 'GitHub', 'GitHub Actions'],
        whyItMatters: 'All code lives in Git. Security-as-code means your rules, pipelines, and automation live there too. Pre-commit hooks are your first line of defense.',
        resources: [
          {
            title: 'Pro Git Book (free)',
            url: 'https://git-scm.com/book/en/v2',
            type: 'book',
            isFree: true,
            priority: 'must',
            note: 'Official free Git book. Chapters 1–3 and 8 (hooks) are the ones you need.',
          },
          {
            title: 'GitHub Skills – GitHub Actions',
            url: 'https://skills.github.com/',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Free interactive GitHub courses. Do "Introduction to GitHub" and "GitHub Actions" courses.',
          },
          {
            title: 'GitHub Actions Official Docs',
            url: 'https://docs.github.com/en/actions',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Reference for workflow syntax, triggers, secrets, and permissions.',
          },
          {
            title: 'Pre-commit Framework',
            url: 'https://pre-commit.com/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'The standard tool for managing pre-commit hooks. You will use this in Lab 2.2.',
          },
        ],
      },
      {
        key: 'phase1_linux',
        title: 'Linux Administration',
        description: 'Permissions, systemd, journalctl, ss/netstat, find, curl',
        tools: ['Linux', 'systemd', 'journalctl', 'ss', 'netstat'],
        whyItMatters: 'Almost every cloud workload runs on Linux. Understanding permissions, processes, and networking at the OS level is non-negotiable for security engineers.',
        resources: [
          {
            title: 'Linux Journey',
            url: 'https://linuxjourney.com',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Free, interactive Linux learning path. Do Grasshopper → Journeyman tracks.',
          },
          {
            title: 'TryHackMe – Linux Fundamentals (3 parts)',
            url: 'https://tryhackme.com/module/linux-fundamentals',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Hands-on rooms with an in-browser Linux machine. Covers permissions, processes, services.',
          },
          {
            title: 'OverTheWire: Bandit (levels 20+)',
            url: 'https://overthewire.org/wargames/bandit/',
            type: 'practice',
            isFree: true,
            priority: 'recommended',
            note: 'Continue past level 20 for networking and process challenges.',
          },
          {
            title: 'systemd by Example',
            url: 'https://systemd-by-example.com/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Practical systemd guide. Covers service management and journalctl queries.',
          },
        ],
      },
      {
        key: 'phase1_docker',
        title: 'Docker Basics',
        description: 'Build, run, volumes, networks, docker-compose',
        tools: ['Docker', 'docker-compose'],
        whyItMatters: 'Containers are the deployment unit in modern infrastructure. You need to understand how they work to harden them, scan them, and write secure Dockerfiles.',
        resources: [
          {
            title: 'Docker Official Get Started Guide',
            url: 'https://docs.docker.com/get-started/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official tutorial. Parts 1–5 cover build, run, compose, and volumes.',
          },
          {
            title: 'Play with Docker (browser-based labs)',
            url: 'https://labs.play-with-docker.com/',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Free in-browser Docker environment. No local setup needed.',
          },
          {
            title: 'Docker Security Best Practices – Snyk',
            url: 'https://snyk.io/blog/10-docker-image-security-best-practices/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Directly relevant to Lab 1.3. Shows exactly what to fix and why.',
          },
          {
            title: 'TryHackMe – Docker Security Room',
            url: 'https://tryhackme.com/room/dockerrodeo',
            type: 'practice',
            isFree: false,
            priority: 'optional',
            note: 'Hands-on Docker security exploitation and hardening.',
          },
        ],
      },
    ],
    labs: [
      {
        key: 'lab1_1',
        title: 'Lab 1.1: Python Security Scanner CLI',
        description: 'Build a CLI that reads a hosts file, checks open ports, and outputs structured JSON results',
        resources: [
          {
            title: 'Python socket module docs',
            url: 'https://docs.python.org/3/library/socket.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Reference for the socket.connect_ex() call that powers port scanning.',
          },
          {
            title: 'argparse tutorial – Real Python',
            url: 'https://realpython.com/command-line-interfaces-python-argparse/',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'How to build a proper CLI interface in Python.',
          },
          {
            title: 'concurrent.futures for parallel scanning',
            url: 'https://docs.python.org/3/library/concurrent.futures.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Makes the scanner fast by checking ports in parallel threads.',
          },
        ],
      },
      {
        key: 'lab1_2',
        title: 'Lab 1.2: Bash Log Parser',
        description: 'Parse auth.log, count failed logins by IP, generate a report and optionally send a Slack alert',
        resources: [
          {
            title: 'grep, awk, sed cheatsheet',
            url: 'https://ryanstutorials.net/linuxtutorial/grep.php',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'Quick reference for the three tools you will use most in this lab.',
          },
          {
            title: 'Slack Incoming Webhooks docs',
            url: 'https://api.slack.com/messaging/webhooks',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to send curl-based alerts to Slack — the alert integration for this lab.',
          },
        ],
      },
      {
        key: 'lab1_3',
        title: 'Lab 1.3: Docker Hardening',
        description: 'Compare an insecure Dockerfile vs a hardened one, run Trivy scans on both, document the difference',
        resources: [
          {
            title: 'Trivy Quickstart',
            url: 'https://aquasecurity.github.io/trivy/latest/getting-started/installation/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Install and run your first Trivy image scan.',
          },
          {
            title: 'Dockerfile best practices – Docker docs',
            url: 'https://docs.docker.com/develop/develop-images/dockerfile_best-practices/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official hardening guide. Use this as your checklist for the secure Dockerfile.',
          },
        ],
      },
    ],
  },
  {
    phase: 2,
    title: 'DevSecOps Core',
    goal: 'Integrate security into CI/CD pipelines',
    weeks: 'Weeks 5–8',
    topics: [
      {
        key: 'phase2_github_actions',
        title: 'GitHub Actions',
        description: 'Workflow syntax, triggers, jobs, secrets, matrix builds, conditions',
        tools: ['GitHub Actions', 'YAML'],
        whyItMatters: 'GitHub Actions is the most common CI/CD platform. Every security gate you build—SAST, SCA, secrets scanning—runs here. This is DevSecOps in practice.',
        resources: [
          {
            title: 'GitHub Actions Docs – Workflow Syntax',
            url: 'https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The complete reference. Keep this open while writing your first pipelines.',
          },
          {
            title: 'GitHub Skills – GitHub Actions',
            url: 'https://skills.github.com/',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Free interactive course. Teaches triggers, jobs, and secrets in a real repo.',
          },
          {
            title: 'GitHub Actions Security Hardening Guide',
            url: 'https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official security guide. Covers pinned actions, OIDC, and least-privilege tokens — exactly what Lab 2.1 requires.',
          },
          {
            title: 'Reusable Workflows and Secrets – GitHub Docs',
            url: 'https://docs.github.com/en/actions/sharing-automations/reusing-workflows',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to structure scalable pipelines across multiple repositories.',
          },
        ],
      },
      {
        key: 'phase2_sast',
        title: 'SAST: Semgrep + Bandit',
        description: 'Integrate static analysis into pipelines, triage and tune results, write custom rules',
        tools: ['Semgrep', 'Bandit'],
        whyItMatters: 'SAST catches vulnerabilities before code ships. Knowing how to integrate, tune, and not cry-wolf with false positives is what separates a security engineer from a tool operator.',
        resources: [
          {
            title: 'Semgrep Learn (interactive rule writing)',
            url: 'https://semgrep.dev/learn',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Browser-based interactive Semgrep training. Learn to write patterns, not just run them.',
          },
          {
            title: 'Semgrep Docs – Writing Rules',
            url: 'https://semgrep.dev/docs/writing-rules/overview/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete guide to Semgrep rule syntax. Custom rules are what employers want.',
          },
          {
            title: 'Bandit Docs',
            url: 'https://bandit.readthedocs.io/en/latest/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Python-specific static analyzer. Easy to run, useful for finding common Python security issues.',
          },
          {
            title: 'Semgrep Registry (5,000+ open-source rules)',
            url: 'https://semgrep.dev/explore',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Browse and understand existing rules before writing your own.',
          },
        ],
      },
      {
        key: 'phase2_sca',
        title: 'SCA: Dependency Scanning',
        description: 'Snyk or OWASP Dependency-Check, CVSS threshold enforcement, license scanning',
        tools: ['Snyk', 'OWASP Dependency-Check'],
        whyItMatters: 'Most vulnerabilities in modern apps come from dependencies, not custom code. Automated SCA in CI is table stakes for any DevSecOps pipeline.',
        resources: [
          {
            title: 'Snyk Learn – Open Source Security',
            url: 'https://learn.snyk.io/catalog/?type=lesson',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Free lessons on SCA concepts, CVSS scoring, and dependency risk. No fluff.',
          },
          {
            title: 'OWASP Dependency-Check Docs',
            url: 'https://jeremylong.github.io/DependencyCheck/index.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Free, open-source SCA tool. Use this when you cannot use Snyk in a pipeline.',
          },
          {
            title: 'Understanding CVSS Scores – NVD',
            url: 'https://nvd.nist.gov/vuln-metrics/cvss',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Official CVSS calculator and guide. You need to understand scoring to set meaningful thresholds.',
          },
          {
            title: 'Snyk CLI Docs',
            url: 'https://docs.snyk.io/snyk-cli',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Reference for integrating Snyk into GitHub Actions.',
          },
        ],
      },
      {
        key: 'phase2_secrets',
        title: 'Secret Scanning',
        description: 'Gitleaks, TruffleHog — pre-commit hooks and CI integration, custom patterns',
        tools: ['Gitleaks', 'TruffleHog', 'pre-commit'],
        whyItMatters: 'Leaked credentials are the most common cause of cloud breaches. Pre-commit secret scanning stops the bleeding before it starts.',
        resources: [
          {
            title: 'Gitleaks GitHub Repo + Docs',
            url: 'https://github.com/gitleaks/gitleaks',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'README contains everything you need. Focus on custom rules (.gitleaks.toml) and CI integration.',
          },
          {
            title: 'Pre-commit Framework Docs',
            url: 'https://pre-commit.com/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to set up hook management. Required for Lab 2.2.',
          },
          {
            title: 'TruffleHog Docs',
            url: 'https://github.com/trufflesecurity/trufflehog',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Alternative to Gitleaks with deeper entropy analysis. Know both tools.',
          },
          {
            title: 'Writing Custom Gitleaks Rules',
            url: 'https://github.com/gitleaks/gitleaks?tab=readme-ov-file#configuration',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to write custom regex patterns for organization-specific secrets.',
          },
        ],
      },
      {
        key: 'phase2_container',
        title: 'Container Security',
        description: 'Trivy, Grype, Hadolint — scan images, enforce policies, Docker best practices',
        tools: ['Trivy', 'Grype', 'Hadolint', 'Docker'],
        whyItMatters: 'Container images ship vulnerable OS packages and misconfigurations constantly. Automated scanning in the pipeline catches this before it reaches production.',
        resources: [
          {
            title: 'Trivy Documentation',
            url: 'https://aquasecurity.github.io/trivy/latest/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete Trivy docs. Focus on image scanning, GitHub Actions integration, and severity thresholds.',
          },
          {
            title: 'Hadolint – Dockerfile Linter',
            url: 'https://github.com/hadolint/hadolint',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Paste your Dockerfile at hadolint.github.io/hadolint/ to see issues immediately.',
          },
          {
            title: 'NIST Container Security Guide (SP 800-190)',
            url: 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-190.pdf',
            type: 'book',
            isFree: true,
            priority: 'recommended',
            note: 'The definitive container security standard. Skim the threat model section — it comes up in interviews.',
          },
          {
            title: 'Grype Docs',
            url: 'https://github.com/anchore/grype',
            type: 'repo',
            isFree: true,
            priority: 'optional',
            note: 'Alternative to Trivy. Know it exists, understand the difference.',
          },
        ],
      },
      {
        key: 'phase2_pipeline_hardening',
        title: 'Pipeline Hardening',
        description: 'Pinned actions, OIDC for cloud auth, least-privilege tokens, supply chain security',
        tools: ['GitHub Actions', 'OIDC', 'Sigstore'],
        whyItMatters: 'CI/CD pipelines are high-value targets. Compromised pipelines can push malicious code to production. Hardening them is part of the job.',
        resources: [
          {
            title: 'GitHub Actions Security Hardening – Official Docs',
            url: 'https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Covers pinned actions, OIDC, script injection, and token permissions.',
          },
          {
            title: 'Configuring OIDC in GitHub Actions',
            url: 'https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to authenticate to AWS/Azure without storing long-lived credentials in GitHub secrets.',
          },
          {
            title: 'StepSecurity Action Hardening Tool',
            url: 'https://app.stepsecurity.io/',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Free tool that auto-pins your GitHub Actions and adds security fixes. Run it on your pipelines.',
          },
          {
            title: 'SLSA Framework',
            url: 'https://slsa.dev/',
            type: 'article',
            isFree: true,
            priority: 'optional',
            note: 'Supply chain security framework. Shows up in senior SE interviews — know what it is.',
          },
        ],
      },
      {
        key: 'phase2_sbom',
        title: 'SBOM Basics',
        description: 'Syft, CycloneDX — generate and consume software bills of materials',
        tools: ['Syft', 'CycloneDX'],
        whyItMatters: 'Regulatory requirements and enterprise customers increasingly demand SBOMs. Knowing how to generate and use them is becoming a baseline expectation.',
        resources: [
          {
            title: 'Syft by Anchore – Docs & GitHub',
            url: 'https://github.com/anchore/syft',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'The most common SBOM generation tool. Generate one for a Docker image in 5 minutes.',
          },
          {
            title: 'CISA SBOM Overview',
            url: 'https://www.cisa.gov/sbom',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Government SBOM guidance. Good background on why organizations are requiring SBOMs.',
          },
          {
            title: 'CycloneDX Standard',
            url: 'https://cyclonedx.org/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'The dominant SBOM format. Understand the spec so you can explain it in interviews.',
          },
        ],
      },
    ],
    labs: [
      {
        key: 'lab2_1',
        title: 'Lab 2.1: Full GitHub Actions Security Pipeline',
        description: 'Build a pipeline with 5 gate categories: SAST (Semgrep) + SCA + secrets (Gitleaks) + container (Trivy) + IaC (Checkov)',
        resources: [
          {
            title: 'Semgrep GitHub Action',
            url: 'https://github.com/marketplace/actions/semgrep',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Official Semgrep Action for GitHub. Copy the YAML, customize the rules.',
          },
          {
            title: 'Trivy GitHub Action',
            url: 'https://github.com/marketplace/actions/aqua-security-trivy',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Official Trivy Action. Configure severity thresholds to fail the build on CRITICAL.',
          },
          {
            title: 'DevSecOps Pipeline Reference Architecture – OWASP',
            url: 'https://owasp.org/www-project-devsecops-guideline/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'OWASP\'s DevSecOps guide. Use it to understand why each gate type exists.',
          },
        ],
      },
      {
        key: 'lab2_2',
        title: 'Lab 2.2: Pre-commit Hooks',
        description: 'Set up Gitleaks pre-commit hook plus a custom pattern hook that catches company-specific sensitive strings',
        resources: [
          {
            title: 'Gitleaks pre-commit configuration',
            url: 'https://github.com/gitleaks/gitleaks?tab=readme-ov-file#pre-commit',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Exact YAML config needed to add Gitleaks as a pre-commit hook.',
          },
          {
            title: 'Writing a custom pre-commit hook in bash',
            url: 'https://pre-commit.com/#new-hooks',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to write your own hook for custom pattern matching.',
          },
        ],
      },
    ],
  },
  {
    phase: 3,
    title: 'Cloud Security Engineering',
    goal: 'Elevate cloud knowledge from operational to engineering execution',
    weeks: 'Weeks 9–12',
    topics: [
      {
        key: 'phase3_aws_iam',
        title: 'AWS IAM Engineering',
        description: 'Policies, roles, permission boundaries, SCPs, IAM Access Analyzer',
        tools: ['AWS IAM', 'IAM Access Analyzer', 'AWS Organizations'],
        whyItMatters: 'IAM is the most complex and highest-impact part of AWS security. Engineers who can write least-privilege policies and use SCPs are rare and valuable.',
        resources: [
          {
            title: 'AWS IAM Docs – Policies and Permissions',
            url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official reference. Read the policy evaluation logic section — it is tested in every AWS security interview.',
          },
          {
            title: 'Flaws.cloud – IAM Exploitation Lab',
            url: 'http://flaws.cloud',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Free, intentionally vulnerable AWS environment. Levels 1–6 teach IAM misconfigs through exploitation. Build before you can defend.',
          },
          {
            title: 'AWS re:Inforce – IAM Best Practices (YouTube)',
            url: 'https://www.youtube.com/results?search_query=aws+reinforce+iam+best+practices',
            type: 'video',
            isFree: true,
            priority: 'recommended',
            note: 'AWS engineers explaining IAM design patterns. Watch one per topic.',
          },
          {
            title: 'IAM Access Analyzer Docs',
            url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Automated least-privilege enforcement tool. Required for Project 4.',
          },
          {
            title: 'CloudGoat – Vulnerable AWS Environment',
            url: 'https://github.com/RhinoSecurityLabs/cloudgoat',
            type: 'practice',
            isFree: true,
            priority: 'optional',
            note: 'Terraform-deployed vulnerable AWS labs from Rhino Security. Harder than flaws.cloud.',
          },
        ],
      },
      {
        key: 'phase3_aws_s3',
        title: 'AWS S3 Security',
        description: 'Bucket policies, public access blocks, encryption enforcement, Object Lock',
        tools: ['AWS S3', 'AWS Config'],
        whyItMatters: 'S3 misconfiguration is still one of the top causes of data breaches. Automating detection and remediation of public buckets is a core security engineering task.',
        resources: [
          {
            title: 'AWS S3 Security Best Practices',
            url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official AWS guide. Contains every control you need to implement in Lab 3.1.',
          },
          {
            title: 'Flaws.cloud Level 1–2 (S3 buckets)',
            url: 'http://flaws.cloud',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'First two levels focus on S3 misconfigurations. Exploit them first, then know how to prevent them.',
          },
          {
            title: 'S3 Block Public Access – AWS Docs',
            url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'The most important single S3 control. Understand all four settings.',
          },
        ],
      },
      {
        key: 'phase3_cloudtrail',
        title: 'AWS CloudTrail',
        description: 'Enable, configure, analyze logs, detect anomalies with Athena queries',
        tools: ['AWS CloudTrail', 'AWS Athena', 'S3'],
        whyItMatters: 'CloudTrail is your audit log for everything in AWS. Detection engineering in the cloud starts here.',
        resources: [
          {
            title: 'AWS CloudTrail Docs',
            url: 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Reference for enabling multi-region trails, log file validation, and S3 delivery.',
          },
          {
            title: 'Querying CloudTrail with Athena – AWS Docs',
            url: 'https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to write SQL queries against CloudTrail logs. Essential for Phase 5 detection work.',
          },
          {
            title: 'CloudTrail Threat Hunting Queries – GitHub',
            url: 'https://github.com/elastic/detection-rules/tree/main/rules/aws',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Real detection rules for CloudTrail events. Study these to understand attack patterns.',
          },
        ],
      },
      {
        key: 'phase3_guardduty',
        title: 'AWS GuardDuty',
        description: 'Findings, suppression rules, Lambda auto-response, EventBridge integration',
        tools: ['AWS GuardDuty', 'AWS Lambda', 'EventBridge'],
        whyItMatters: 'GuardDuty gives you threat detection for free — but automating responses to findings is what makes it operational.',
        resources: [
          {
            title: 'AWS GuardDuty Docs',
            url: 'https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete reference. Focus on the Finding Types section — you need to know what each finding means.',
          },
          {
            title: 'Automating GuardDuty Response with Lambda – AWS Blog',
            url: 'https://aws.amazon.com/blogs/security/how-to-use-amazon-guardduty-and-aws-lambda-to-do-real-time-remediation/',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'Walkthrough of the EventBridge → Lambda auto-response pattern.',
          },
          {
            title: 'GuardDuty Finding Types Reference',
            url: 'https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-active.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Bookmark this. Every finding type, what triggers it, and what it means.',
          },
        ],
      },
      {
        key: 'phase3_security_hub',
        title: 'AWS Security Hub',
        description: 'Enable standards, aggregate findings, custom findings via ASFF, multi-account',
        tools: ['AWS Security Hub', 'ASFF'],
        whyItMatters: 'Security Hub is the control plane for AWS security posture. Engineering custom findings and integrations into it is a senior-level skill.',
        resources: [
          {
            title: 'AWS Security Hub Docs',
            url: 'https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Reference for enabling standards (CIS, NIST, PCI), aggregating findings, and custom insights.',
          },
          {
            title: 'ASFF (Amazon Security Finding Format) Reference',
            url: 'https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The JSON schema for custom findings. You will use this in Lab 3.1 to import scanner results.',
          },
          {
            title: 'Custom Security Hub Findings with Boto3 – AWS Blog',
            url: 'https://aws.amazon.com/blogs/security/how-to-build-a-multi-region-aws-security-hub-analytical-pipeline/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Real-world example of importing custom findings programmatically.',
          },
        ],
      },
      {
        key: 'phase3_aws_config',
        title: 'AWS Config',
        description: 'Managed rules, custom rules via Lambda, remediation actions, conformance packs',
        tools: ['AWS Config', 'AWS Lambda'],
        whyItMatters: 'Config gives you continuous compliance monitoring. Custom rules let you enforce organization-specific controls that AWS does not cover.',
        resources: [
          {
            title: 'AWS Config Managed Rules Reference',
            url: 'https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Full list of built-in rules. Study the S3, IAM, and CloudTrail rules first.',
          },
          {
            title: 'Writing Custom Config Rules with Lambda',
            url: 'https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_lambda-functions.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to write Python Lambda functions that evaluate custom compliance rules.',
          },
          {
            title: 'AWS Config Conformance Packs',
            url: 'https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html',
            type: 'docs',
            isFree: true,
            priority: 'optional',
            note: 'Pre-built rule collections for CIS, HIPAA, PCI. Useful context for compliance conversations.',
          },
        ],
      },
      {
        key: 'phase3_vpc',
        title: 'VPC Security',
        description: 'Security groups, NACLs, VPC flow logs, PrivateLink, endpoints',
        tools: ['AWS VPC', 'VPC Flow Logs'],
        whyItMatters: 'Network security in AWS is not firewall rules — it is VPC design. Engineers need to understand how traffic flows before they can secure it.',
        resources: [
          {
            title: 'AWS VPC Security Best Practices',
            url: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-best-practices.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official guide. Covers security group rules, NACLs, and flow log analysis.',
          },
          {
            title: 'VPC Flow Logs – Enabling and Querying with Athena',
            url: 'https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-athena.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to query network traffic logs. Key skill for incident response and detection.',
          },
          {
            title: 'AWS re:Invent – VPC Deep Dive (YouTube)',
            url: 'https://www.youtube.com/results?search_query=aws+reinvent+vpc+deep+dive+security',
            type: 'video',
            isFree: true,
            priority: 'recommended',
            note: 'AWS engineers explaining VPC internals. Essential for understanding what security groups actually do.',
          },
        ],
      },
      {
        key: 'phase3_kms_secrets',
        title: 'KMS and Secrets Manager',
        description: 'Key policies, CMKs, automatic rotation, cross-account access, Lambda secrets retrieval',
        tools: ['AWS KMS', 'AWS Secrets Manager'],
        whyItMatters: 'Encryption at rest and secrets management are baseline controls. Automating key rotation and secrets injection into workloads is a core engineering task.',
        resources: [
          {
            title: 'AWS Secrets Manager Docs',
            url: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Full reference. Focus on automatic rotation and Lambda integration — used in Project 4.',
          },
          {
            title: 'AWS KMS Concepts and Key Policies',
            url: 'https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Understand CMKs vs AWS-managed keys, key policies vs IAM policies.',
          },
          {
            title: 'Boto3 Secrets Manager – Code Examples',
            url: 'https://docs.aws.amazon.com/code-library/latest/ug/secretsmanager_example_secretsmanager_GetSecretValue_section.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Python code snippets for retrieving secrets in Lambda and EC2.',
          },
        ],
      },
      {
        key: 'phase3_boto3',
        title: 'Boto3 Automation',
        description: 'Python automation against all AWS security services — IAM, S3, EC2, CloudTrail, GuardDuty, Security Hub',
        tools: ['Python', 'Boto3', 'AWS SDK'],
        whyItMatters: 'Boto3 is how you automate everything in AWS. If you cannot script AWS, you are still doing security manually.',
        resources: [
          {
            title: 'Boto3 Documentation',
            url: 'https://boto3.amazonaws.com/v1/documentation/api/latest/index.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The complete reference. Use the search bar to find any service client method.',
          },
          {
            title: 'AWS Code Examples Library (Python/Boto3)',
            url: 'https://docs.aws.amazon.com/code-library/latest/ug/python_3_code_examples.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Official Boto3 code examples for every AWS service. Start here before writing from scratch.',
          },
          {
            title: 'Moto – AWS Mocking Library for Python',
            url: 'https://docs.getmoto.org/en/latest/',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Mock AWS services in your tests without real API calls. Used in Lab 3.1 for unit tests.',
          },
          {
            title: 'Practical AWS Security Automation – Packt (book)',
            url: 'https://www.packtpub.com/en-us/product/aws-security-cookbook-9781838826253',
            type: 'book',
            isFree: false,
            priority: 'optional',
            note: 'Practical Boto3 security automation recipes. Worth borrowing from a library.',
          },
        ],
      },
      {
        key: 'phase3_azure',
        title: 'Azure Security Engineering',
        description: 'Defender for Cloud, Entra ID, Key Vault, Monitor, Policy, RBAC',
        tools: ['Azure Defender', 'Entra ID', 'Azure Policy', 'Azure Monitor'],
        whyItMatters: 'Most enterprises are multi-cloud. Your Azure background needs to be at the same engineering depth as your AWS knowledge.',
        resources: [
          {
            title: 'Microsoft Learn – AZ-500 Security Technologies',
            url: 'https://learn.microsoft.com/en-us/certifications/exams/az-500/',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Free Microsoft learning path. Covers all Azure security services at engineering depth. AZ-500 is the cert to target.',
          },
          {
            title: 'Microsoft Defender for Cloud Docs',
            url: 'https://learn.microsoft.com/en-us/azure/defender-for-cloud/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Reference for CSPM, workload protection, and Secure Score.',
          },
          {
            title: 'Azure Policy Docs',
            url: 'https://learn.microsoft.com/en-us/azure/governance/policy/overview',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to enforce compliance controls across Azure subscriptions — the Azure equivalent of SCPs.',
          },
          {
            title: 'KC7 Cyber – KQL Detection Practice (free)',
            url: 'https://kc7cyber.com/',
            type: 'practice',
            isFree: true,
            priority: 'recommended',
            note: 'Free, gamified KQL practice against realistic Azure security data. Excellent for building Sentinel skills.',
          },
        ],
      },
      {
        key: 'phase3_terraform',
        title: 'Terraform',
        description: 'HCL syntax, resources, modules, state management, variables, workspaces',
        tools: ['Terraform', 'HCL'],
        whyItMatters: 'Infrastructure as Code is how cloud environments are built. Security engineers who can read and write Terraform can enforce security at the design stage.',
        resources: [
          {
            title: 'HashiCorp Terraform Tutorials',
            url: 'https://developer.hashicorp.com/terraform/tutorials',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'Official free tutorials. Do the AWS path: Get Started → Modules → State.',
          },
          {
            title: 'Terraform AWS Provider Docs',
            url: 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Reference for every AWS resource you can manage with Terraform. Bookmark it.',
          },
          {
            title: 'Terraform Best Practices – Anton Babenko',
            url: 'https://www.terraform-best-practices.com/',
            type: 'book',
            isFree: true,
            priority: 'recommended',
            note: 'Free book on Terraform project structure and module design. Essential before Projects 3 and 4.',
          },
        ],
      },
      {
        key: 'phase3_iac_scanning',
        title: 'IaC Security Scanning',
        description: 'Checkov, tfsec — scan Terraform and CloudFormation, integrate into CI/CD',
        tools: ['Checkov', 'tfsec'],
        whyItMatters: 'Shifting IaC security left catches misconfigurations before they are deployed. This is the highest-leverage security gate in the infrastructure pipeline.',
        resources: [
          {
            title: 'Checkov Documentation',
            url: 'https://www.checkov.io/1.Welcome/What%20is%20Checkov.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Full Checkov docs. Focus on CLI usage, custom checks, and GitHub Actions integration.',
          },
          {
            title: 'Checkov GitHub Action',
            url: 'https://github.com/marketplace/actions/checkov-github-action',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Plug-and-play GitHub Action for Terraform scanning. Used directly in Lab 3.2.',
          },
          {
            title: 'tfsec Docs',
            url: 'https://aquasecurity.github.io/tfsec/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Alternative to Checkov. Know both — different jobs use different tools.',
          },
          {
            title: 'Writing Custom Checkov Policies',
            url: 'https://www.checkov.io/3.Custom%20Policies/Custom%20Policies%20Overview.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to write custom checks in Python. Differentiates you from someone who just runs the default ruleset.',
          },
        ],
      },
      {
        key: 'phase3_prowler',
        title: 'Prowler',
        description: 'Run AWS/Azure/GCP assessments, interpret findings, write custom checks',
        tools: ['Prowler'],
        whyItMatters: 'Prowler gives you a full cloud security posture assessment from the command line. Custom checks let you enforce controls beyond the built-in library.',
        resources: [
          {
            title: 'Prowler Documentation',
            url: 'https://docs.prowler.com/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Full docs. Start with Quick Start, then explore the check library and output formats.',
          },
          {
            title: 'Prowler GitHub Repository',
            url: 'https://github.com/prowler-cloud/prowler',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Study the existing check code to understand how to write your own.',
          },
          {
            title: 'Writing Custom Prowler Checks',
            url: 'https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/checks/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to extend Prowler with organization-specific compliance checks.',
          },
        ],
      },
    ],
    labs: [
      {
        key: 'lab3_1',
        title: 'Lab 3.1: Boto3 AWS Misconfig Scanner',
        description: 'Python CLI that checks S3 + IAM + EC2 + CloudTrail for common misconfigurations and outputs a JSON + HTML report',
        resources: [
          {
            title: 'Boto3 S3 Client Reference',
            url: 'https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'get_bucket_acl, get_bucket_policy_status, get_bucket_encryption — the calls you need.',
          },
          {
            title: 'Prowler Check Source Code (Python examples)',
            url: 'https://github.com/prowler-cloud/prowler/tree/master/prowler/providers/aws/services',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Read Prowler\'s actual check implementations to understand the pattern before writing your own.',
          },
        ],
      },
      {
        key: 'lab3_2',
        title: 'Lab 3.2: Terraform + Checkov in GitHub Actions',
        description: 'Write intentionally misconfigured Terraform, run Checkov in CI, fix the failures, document the before/after',
        resources: [
          {
            title: 'Terraform AWS S3 Misconfiguration Examples',
            url: 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Use the docs to understand each argument, then deliberately omit security settings to create failures.',
          },
          {
            title: 'Checkov Checks List – AWS',
            url: 'https://www.checkov.io/5.Policy%20Index/terraform.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Full list of Checkov rules. Use this to pick which misconfigurations to include in your Terraform.',
          },
        ],
      },
    ],
  },
  {
    phase: 4,
    title: 'Application Security Engineering',
    goal: 'Add AppSec and API security depth',
    weeks: 'Weeks 13–16',
    topics: [
      {
        key: 'phase4_owasp_top10',
        title: 'OWASP Top 10 (2021)',
        description: 'All 10 categories, hands-on exploitation in DVWA and Juice Shop',
        tools: ['DVWA', 'OWASP Juice Shop', 'Burp Suite'],
        whyItMatters: 'AppSec interviews always start here. You need to demonstrate exploitation, not just name the categories.',
        resources: [
          {
            title: 'PortSwigger Web Security Academy (free)',
            url: 'https://portswigger.net/web-security',
            type: 'course',
            isFree: true,
            priority: 'must',
            note: 'The best free AppSec learning resource in existence. Labs for every OWASP Top 10 category with guided and unguided versions.',
          },
          {
            title: 'OWASP Juice Shop – Companion Guide',
            url: 'https://pwning.owasp-juice.shop/',
            type: 'book',
            isFree: true,
            priority: 'must',
            note: 'Free companion guide to Juice Shop. Read the challenge descriptions before attempting, not after.',
          },
          {
            title: 'OWASP Top 10 Official Docs (2021)',
            url: 'https://owasp.org/Top10/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'The source. Read the description, mapped CWEs, and prevention sections for each category.',
          },
          {
            title: 'TryHackMe – OWASP Top 10 Room',
            url: 'https://tryhackme.com/room/owasptop10',
            type: 'practice',
            isFree: true,
            priority: 'recommended',
            note: 'Hands-on exploitation of all 10 categories in a guided environment.',
          },
        ],
      },
      {
        key: 'phase4_api_security',
        title: 'API Security',
        description: 'Auth flaws, IDOR, rate limiting, JWT attacks, OWASP API Top 10',
        tools: ['Postman', 'Burp Suite', 'JWT'],
        whyItMatters: 'APIs are the attack surface of modern applications. Security engineers are expected to test and design secure APIs.',
        resources: [
          {
            title: 'PortSwigger API Testing Labs',
            url: 'https://portswigger.net/web-security/api-testing',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Hands-on API exploitation labs. Covers BOLA/IDOR, auth bypass, mass assignment.',
          },
          {
            title: 'OWASP API Security Top 10',
            url: 'https://owasp.org/www-project-api-security/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The API-specific companion to OWASP Top 10. Read the API1–API10 descriptions in full.',
          },
          {
            title: 'JWT Security – PortSwigger',
            url: 'https://portswigger.net/web-security/jwt',
            type: 'practice',
            isFree: true,
            priority: 'recommended',
            note: 'JWT attack labs: alg:none, signature bypass, key confusion. Essential for API security interviews.',
          },
          {
            title: 'crAPI – Completely Ridiculous API (vulnerable practice app)',
            url: 'https://github.com/OWASP/crAPI',
            type: 'practice',
            isFree: true,
            priority: 'recommended',
            note: 'OWASP\'s intentionally vulnerable API app. Covers all OWASP API Top 10 categories.',
          },
        ],
      },
      {
        key: 'phase4_threat_modeling',
        title: 'Threat Modeling',
        description: 'STRIDE applied to real systems, data flow diagrams, attack trees',
        tools: ['STRIDE', 'OWASP Threat Dragon'],
        whyItMatters: 'Threat modeling is the skill that separates reactive security from proactive security engineering. It is asked about in almost every SE interview.',
        resources: [
          {
            title: 'Threat Modeling: Designing for Security – Adam Shostack',
            url: 'https://www.amazon.com/Threat-Modeling-Designing-Adam-Shostack/dp/1118809998',
            type: 'book',
            isFree: false,
            priority: 'must',
            note: 'The definitive book. At minimum read Chapters 1–4. Author is the creator of the 4-question framework used at Microsoft.',
          },
          {
            title: 'OWASP Threat Dragon (free tool)',
            url: 'https://owasp.org/www-project-threat-dragon/',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Free web-based threat modeling tool. Use this to build your data flow diagrams.',
          },
          {
            title: 'STRIDE Threat Model – Microsoft Docs',
            url: 'https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Microsoft\'s STRIDE guide. Good reference for the threat categories and mitigations.',
          },
          {
            title: 'Elevation of Privilege Card Game',
            url: 'https://shostack.org/games/elevation-of-privilege',
            type: 'tool',
            isFree: true,
            priority: 'optional',
            note: 'Free card game for learning threat modeling. Unconventional but effective.',
          },
        ],
      },
      {
        key: 'phase4_dast',
        title: 'DAST',
        description: 'OWASP ZAP or Nuclei — automated scanning against vulnerable apps, CI integration',
        tools: ['OWASP ZAP', 'Nuclei'],
        whyItMatters: 'Dynamic testing catches runtime vulnerabilities that SAST misses. Automating it in CI closes the loop between development and deployment.',
        resources: [
          {
            title: 'OWASP ZAP Documentation',
            url: 'https://www.zaproxy.org/docs/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete ZAP docs. Start with the Getting Started guide, then the Automation Framework.',
          },
          {
            title: 'ZAP GitHub Action',
            url: 'https://github.com/marketplace/actions/owasp-zap-full-scan',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Plug-in ZAP into your pipeline. Use the Full Scan action for Project 5.',
          },
          {
            title: 'Nuclei Templates Repository',
            url: 'https://github.com/projectdiscovery/nuclei-templates',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: '7,000+ vulnerability templates. Study template syntax to write your own.',
          },
        ],
      },
      {
        key: 'phase4_secure_code_review',
        title: 'Secure Code Review',
        description: 'Reviewing Python, JavaScript, YAML, and Terraform for security issues',
        tools: ['Semgrep', 'manual review'],
        whyItMatters: 'Code review is a core part of the security engineer job description. You need to give specific, actionable feedback — not just flag things as "bad".',
        resources: [
          {
            title: 'Secure Code Review Checklist – OWASP',
            url: 'https://owasp.org/www-project-code-review-guide/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'OWASP\'s code review methodology. Use this as a checklist structure.',
          },
          {
            title: 'Python Security Vulnerabilities – Common Patterns',
            url: 'https://python.readthedocs.io/en/latest/library/security_warnings.html',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'The patterns that show up in Python security reviews: eval, subprocess shell=True, pickle, yaml.load.',
          },
          {
            title: 'Vulnerable Python Code Examples – GitHub',
            url: 'https://github.com/dobin/juice-shop',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Practice reviewing real vulnerable code before you review someone else\'s.',
          },
          {
            title: 'GitHub Advanced Security Code Scanning Docs',
            url: 'https://docs.github.com/en/code-security/code-scanning',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How GitHub\'s code scanning works. Know the tooling you will use on the job.',
          },
        ],
      },
      {
        key: 'phase4_web_fundamentals',
        title: 'Web Security Fundamentals',
        description: 'CORS, CSP, SSRF, deserialization, clickjacking, security headers',
        tools: ['Burp Suite', 'browser devtools'],
        whyItMatters: 'These concepts come up constantly in code review and architecture discussions. You need them cold.',
        resources: [
          {
            title: 'PortSwigger – CORS, SSRF, Clickjacking Labs',
            url: 'https://portswigger.net/web-security/all-topics',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Do the CORS, SSRF, Clickjacking, and HTTP Host Header labs. Each topic has theory + labs.',
          },
          {
            title: 'Content Security Policy (CSP) – MDN',
            url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete CSP reference. Understand directives and how to write a strong policy.',
          },
          {
            title: 'SecurityHeaders.com',
            url: 'https://securityheaders.com/',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Scan any URL to see its security headers. Use it to understand what good looks like.',
          },
          {
            title: 'OWASP Deserialization Cheat Sheet',
            url: 'https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Deserialization comes up in AppSec interviews. This cheat sheet covers the main risks.',
          },
        ],
      },
    ],
    labs: [
      {
        key: 'lab4_1',
        title: 'Lab 4.1: Full Juice Shop Security Assessment',
        description: 'Complete security assessment combining SAST + DAST + SCA + manual testing + threat model — produce a professional report',
        resources: [
          {
            title: 'OWASP Juice Shop Source Code (GitHub)',
            url: 'https://github.com/juice-shop/juice-shop',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'Clone the repo to run SAST against the source code.',
          },
          {
            title: 'OWASP Testing Guide',
            url: 'https://owasp.org/www-project-web-security-testing-guide/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'The methodology guide for your manual testing phase.',
          },
          {
            title: 'Pentest Report Template – PentestHQ',
            url: 'https://github.com/hmaverickadams/TCM-Security-Sample-Pentest-Report',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Real pentest report template. Model your assessment report after this.',
          },
        ],
      },
    ],
  },
  {
    phase: 5,
    title: 'Detection Engineering',
    goal: 'Bridge analyst skills into engineering output',
    weeks: 'Weeks 17–20',
    topics: [
      {
        key: 'phase5_sigma',
        title: 'Sigma Rules',
        description: 'Write Sigma rules from scratch for AWS, Linux, Windows, and container events',
        tools: ['Sigma', 'sigma-cli', 'sigmac'],
        whyItMatters: 'Sigma is the YARA of detection. Writing portable, high-fidelity rules is a core detection engineering skill and differentiates you from analysts who only consume rules.',
        resources: [
          {
            title: 'Sigma HQ – Official Specification',
            url: 'https://sigmahq.io/docs/basics/rules.html',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The complete Sigma rule specification. Read it fully before writing your first rule.',
          },
          {
            title: 'SigmaHQ Rule Repository (GitHub)',
            url: 'https://github.com/SigmaHQ/sigma',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'Study existing rules before writing new ones. Focus on the aws/, linux/, and windows/ directories.',
          },
          {
            title: 'Sigma CLI Docs',
            url: 'https://github.com/SigmaHQ/sigma-cli',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to validate and convert rules with sigma-cli. Required for Lab 5.1 CI validation.',
          },
          {
            title: 'Uncoder.io – Sigma Rule Converter',
            url: 'https://uncoder.io/',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Convert Sigma rules to Splunk SPL, KQL, QRadar queries. Useful for testing your rules.',
          },
          {
            title: 'Writing Sigma Rules – Florian Roth Blog',
            url: 'https://www.nextron-systems.com/2018/02/10/write-sigma-rules/',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Guide by the creator of Sigma. Explains the design philosophy and best practices.',
          },
        ],
      },
      {
        key: 'phase5_kql',
        title: 'KQL for Azure Sentinel',
        description: 'Detection queries, scheduled analytics, watchlists, hunting queries',
        tools: ['KQL', 'Azure Sentinel', 'Log Analytics'],
        whyItMatters: 'KQL is mandatory for Azure-focused detection engineering. With your Azure background, this is the skill that unlocks the engineering tier.',
        resources: [
          {
            title: 'KC7 Cyber – Free KQL Security Training',
            url: 'https://kc7cyber.com/',
            type: 'practice',
            isFree: true,
            priority: 'must',
            note: 'Gamified KQL training against realistic security data. The best free way to learn KQL for detection.',
          },
          {
            title: 'Microsoft KQL Reference Docs',
            url: 'https://learn.microsoft.com/en-us/kusto/query/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'Complete KQL language reference. Bookmark the summarize, project, where, and join operators.',
          },
          {
            title: 'Microsoft Sentinel Analytics Rules – GitHub',
            url: 'https://github.com/Azure/Azure-Sentinel/tree/master/Detections',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: '1,500+ production detection queries from Microsoft. Study these to understand real-world KQL patterns.',
          },
          {
            title: 'MustLearnKQL – Free Course',
            url: 'https://github.com/rod-trent/MustLearnKQL',
            type: 'course',
            isFree: true,
            priority: 'recommended',
            note: '30-day KQL challenge with daily exercises. Good structure if you need guided practice.',
          },
        ],
      },
      {
        key: 'phase5_cloudtrail_analysis',
        title: 'CloudTrail Analysis Patterns',
        description: 'Privilege escalation, data exfiltration, API abuse, persistence patterns in CloudTrail',
        tools: ['AWS CloudTrail', 'Athena', 'Python'],
        whyItMatters: 'CloudTrail is the primary data source for AWS threat detection. Knowing the attack patterns in CloudTrail logs is what you build detections for.',
        resources: [
          {
            title: 'AWS CloudTrail Threat Detection – Panther Blog',
            url: 'https://panther.com/blog/detecting-aws-attacks-with-cloudtrail/',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'Real CloudTrail attack patterns with example log events. Build your detections around these.',
          },
          {
            title: 'CloudTrail Privilege Escalation Techniques – Rhino Security',
            url: 'https://rhinosecuritylabs.com/aws/aws-privilege-escalation-methods-mitigation/',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: '21 AWS privilege escalation methods, each with the CloudTrail API calls that reveal them.',
          },
          {
            title: 'Elastic Detection Rules – AWS (GitHub)',
            url: 'https://github.com/elastic/detection-rules/tree/main/rules/aws',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Production-grade AWS detection rules in Elasticsearch EQL. Study the logic to understand what to detect.',
          },
        ],
      },
      {
        key: 'phase5_detection_as_code',
        title: 'Detection-as-Code',
        description: 'Sigma + Git + CI/CD validation pipeline, versioned detection library',
        tools: ['Sigma', 'GitHub Actions', 'sigma-cli'],
        whyItMatters: 'Treating detections as code — with versioning, testing, and CI validation — is the engineering approach that most organizations have not implemented yet.',
        resources: [
          {
            title: 'Detection-as-Code – Panther Labs Guide',
            url: 'https://panther.com/detection-as-code-whitepaper/',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'The definitive guide to the detection-as-code philosophy and implementation patterns.',
          },
          {
            title: 'Testing Sigma Rules with sigma-cli',
            url: 'https://github.com/SigmaHQ/sigma-cli?tab=readme-ov-file#usage',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to validate Sigma rules in a CI pipeline — the core of Lab 5.1.',
          },
          {
            title: 'Sublime Security – Detection Engineering Blog',
            url: 'https://sublime.security/blog',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Practical detection engineering posts from a team doing it at scale.',
          },
        ],
      },
      {
        key: 'phase5_mitre',
        title: 'MITRE ATT&CK Mapping',
        description: 'Tag detections to ATT&CK techniques, use Navigator for coverage mapping',
        tools: ['MITRE ATT&CK', 'ATT&CK Navigator'],
        whyItMatters: 'ATT&CK is the common language for detection coverage. Every employer wants to see ATT&CK-tagged detections and coverage maps.',
        resources: [
          {
            title: 'MITRE ATT&CK Website',
            url: 'https://attack.mitre.org/',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'The primary reference. Study the Cloud matrix (AWS, Azure, GCP) and the Execution, Persistence, and Exfiltration tactics.',
          },
          {
            title: 'ATT&CK Navigator',
            url: 'https://mitre-attack.github.io/attack-navigator/',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Visualize your detection coverage. Create a Navigator layer showing which techniques your rules cover.',
          },
          {
            title: 'ATT&CK for Cloud – AWS Techniques',
            url: 'https://attack.mitre.org/matrices/enterprise/cloud/aws/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Cloud-specific ATT&CK matrix. This is what your CloudTrail detection rules should map to.',
          },
        ],
      },
      {
        key: 'phase5_atomic_red_team',
        title: 'Atomic Red Team',
        description: 'Use Atomic Red Team to test detections, validate rule coverage',
        tools: ['Atomic Red Team', 'Invoke-AtomicRedTeam'],
        whyItMatters: 'You cannot trust a detection you have not tested. Atomic Red Team lets you simulate attacks and verify your rules fire correctly.',
        resources: [
          {
            title: 'Atomic Red Team GitHub',
            url: 'https://github.com/redcanaryco/atomic-red-team',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'The full library of ATT&CK-mapped attack simulations. Browse by technique ID.',
          },
          {
            title: 'Invoke-AtomicRedTeam Docs',
            url: 'https://github.com/redcanaryco/invoke-atomicredteam',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'PowerShell framework for executing Atomic tests. Use this to run tests and verify detections fire.',
          },
        ],
      },
      {
        key: 'phase5_alert_tuning',
        title: 'Alert Tuning and FP Reduction',
        description: 'Baseline normal behavior, add allowlists, tune thresholds, measure alert quality',
        tools: ['Sigma', 'SIEM'],
        whyItMatters: 'High false-positive rates make detections useless. Tuning is the unglamorous work that makes a detection library actually operational.',
        resources: [
          {
            title: 'David Bianco – Pyramid of Pain',
            url: 'https://detect-respond.blogspot.com/2013/03/the-pyramid-of-pain.html',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'The framework for understanding which indicators to detect. Essential conceptual foundation.',
          },
          {
            title: 'Detection Engineering Maturity Matrix',
            url: 'https://kyle-bailey.medium.com/detection-engineering-maturity-matrix-f4f3181a5cc7',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'Framework for assessing and improving your detection program quality.',
          },
          {
            title: 'Sigma Filter Conditions for FP Reduction',
            url: 'https://sigmahq.io/docs/basics/filters.html',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'How to add allowlists and filter conditions to Sigma rules without modifying the core detection.',
          },
        ],
      },
    ],
    labs: [
      {
        key: 'lab5_1',
        title: 'Lab 5.1: Detection Library',
        description: 'Build 5+ Sigma rules for different platforms (AWS, Linux, Windows), tag each to MITRE ATT&CK, add CI validation with sigma-cli, include sample log events',
        resources: [
          {
            title: 'SigmaHQ Cloud Rules (AWS examples)',
            url: 'https://github.com/SigmaHQ/sigma/tree/master/rules/cloud/aws',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'Real AWS Sigma rules to study and model your own against.',
          },
          {
            title: 'sigma-cli GitHub Actions Integration',
            url: 'https://github.com/SigmaHQ/sigma-cli?tab=readme-ov-file#github-actions',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to add sigma-cli validation to your CI pipeline.',
          },
          {
            title: 'ATT&CK Technique Lookup',
            url: 'https://attack.mitre.org/techniques/enterprise/',
            type: 'docs',
            isFree: true,
            priority: 'recommended',
            note: 'Find the right technique ID to tag in each rule\'s tags field.',
          },
        ],
      },
    ],
  },
  {
    phase: 6,
    title: 'Portfolio + Capstone',
    goal: 'Job-ready portfolio and interview preparation',
    weeks: 'Weeks 21–24',
    topics: [
      {
        key: 'phase6_portfolio',
        title: 'Portfolio Project Polish',
        description: 'Finalize all 5 portfolio projects with clean READMEs, live demos where possible, and technical write-ups',
        tools: ['GitHub', 'Markdown'],
        whyItMatters: 'Your GitHub profile is your resume in practice. Employers look at it before interviews. Every project needs to demonstrate the skill it claims to.',
        resources: [
          {
            title: 'Making a Great GitHub Profile README',
            url: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme',
            type: 'docs',
            isFree: true,
            priority: 'must',
            note: 'How to set up a profile README that highlights your security engineering projects.',
          },
          {
            title: 'Awesome README Templates',
            url: 'https://github.com/othneildrew/Best-README-Template',
            type: 'repo',
            isFree: true,
            priority: 'recommended',
            note: 'Template for project READMEs. Every portfolio project should have a README this good.',
          },
        ],
      },
      {
        key: 'phase6_blog',
        title: 'Technical Writing',
        description: 'Write 2 technical blog posts — one on a project, one on a concept you mastered',
        tools: ['Markdown', 'dev.to', 'Medium'],
        whyItMatters: 'Writing forces deep understanding. A well-written post on a specific security topic is also a signal to employers that you think clearly.',
        resources: [
          {
            title: 'dev.to – Free Technical Blog Platform',
            url: 'https://dev.to/',
            type: 'tool',
            isFree: true,
            priority: 'must',
            note: 'Best platform for security engineering posts. Good SEO, active community, no paywall.',
          },
          {
            title: 'The Architecture of Understanding – Writing Guide',
            url: 'https://www.swyx.io/writing-well',
            type: 'article',
            isFree: true,
            priority: 'recommended',
            note: 'How to write technical posts that people actually want to read.',
          },
        ],
      },
      {
        key: 'phase6_interview',
        title: 'Mock Interview Practice',
        description: 'Conduct mock interviews covering technical depth, project walkthroughs, and behavioural questions',
        tools: ['AI Coach', 'LeetCode'],
        whyItMatters: 'Interview performance is a skill that degrades without practice. Consistent mock interviews are the only way to build reliable confidence.',
        resources: [
          {
            title: 'Security Engineering Interview Questions – GitHub',
            url: 'https://github.com/tadwhitaker/Security-Engineer-Interview-Questions',
            type: 'repo',
            isFree: true,
            priority: 'must',
            note: 'Real question bank from security engineering interviews. Use with the AI Coach interview mode.',
          },
          {
            title: 'Cracking the Coding Interview (for scripting rounds)',
            url: 'https://www.crackingthecodinginterview.com/',
            type: 'book',
            isFree: false,
            priority: 'recommended',
            note: 'Some SE roles include Python scripting rounds. Chapters 1–5 cover the relevant patterns.',
          },
        ],
      },
      {
        key: 'phase6_resume',
        title: 'Resume Quantification',
        description: 'Rewrite your resume with quantified impact statements for every security engineering project',
        tools: ['Google Docs'],
        whyItMatters: 'Unquantified security resumes are invisible. "Reduced alert volume by 40%" beats "managed SIEM alerts" every time.',
        resources: [
          {
            title: 'The XYZ Resume Formula – Google',
            url: 'https://www.inc.com/bill-murphy-jr/google-recruiters-say-these-5-words-make-your-resume-literally-unreadable-heres-what-to-say-instead.html',
            type: 'article',
            isFree: true,
            priority: 'must',
            note: 'Accomplished X, measured by Y, by doing Z. This is the formula for every bullet.',
          },
          {
            title: 'Security Engineer Resume Examples – Levels.fyi',
            url: 'https://www.levels.fyi/resume-review/',
            type: 'tool',
            isFree: true,
            priority: 'recommended',
            note: 'Review real security engineer resumes to benchmark your own.',
          },
        ],
      },
    ],
    labs: [],
  },
]

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    key: 'project_1_pipeline',
    title: 'DevSecOps Pipeline',
    description: 'GitHub Actions security pipeline with 5 gate categories: SAST (Semgrep), SCA (Snyk/Dependency-Check), secrets scanning (Gitleaks), container scanning (Trivy), and IaC scanning (Checkov). Applies to a real Python or Node.js application.',
    milestones: [
      'Set up target application repository',
      'Implement SAST gate with Semgrep (Python rules)',
      'Implement SCA gate with CVSS threshold enforcement',
      'Implement secrets scanning with Gitleaks + custom patterns',
      'Implement container scanning with Trivy',
      'Implement IaC scanning with Checkov',
      'Add pipeline hardening: pinned actions, OIDC, minimal permissions',
      'Document all findings and tuning decisions in README',
      'Add SBOM generation with Syft',
    ],
    resumeTalkingPoints: 'Built end-to-end DevSecOps pipeline with 5 automated security gates (SAST, SCA, secrets, container, IaC) reducing manual security review time by X%. Implemented supply chain hardening with pinned actions and OIDC-based cloud authentication.',
    skills: ['GitHub Actions', 'Semgrep', 'Gitleaks', 'Trivy', 'Checkov', 'SBOM', 'Pipeline Hardening'],
  },
  {
    key: 'project_2_aws_scanner',
    title: 'AWS Security Scanner',
    description: 'Python/Boto3 CLI tool that scans AWS environments for misconfigurations across S3, IAM, EC2, and CloudTrail, producing JSON and HTML reports with severity scoring.',
    milestones: [
      'Design CLI interface with argparse (target profile, region, output format)',
      'Implement S3 checks: public access, encryption, versioning, logging',
      'Implement IAM checks: root key usage, MFA, unused roles, overly permissive policies',
      'Implement EC2 checks: public instances, IMDSv2, security group rules',
      'Implement CloudTrail checks: enabled status, multi-region, log validation',
      'Add severity scoring (Critical/High/Medium/Low) for each finding',
      'Generate HTML report with findings summary and remediation guidance',
      'Generate JSON output for ASFF import into Security Hub',
      'Add unit tests with moto (AWS mocking library)',
    ],
    resumeTalkingPoints: 'Developed Python/Boto3 AWS misconfig scanner covering 20+ security checks across S3, IAM, EC2, and CloudTrail with automated HTML and Security Hub-compatible JSON reporting.',
    skills: ['Python', 'Boto3', 'AWS IAM', 'AWS S3', 'AWS Security Hub', 'Security Automation'],
  },
  {
    key: 'project_3_detection_library',
    title: 'Detection Engineering Library',
    description: '10+ production-quality Sigma rules covering AWS, Linux, Windows, and container environments, each tagged to MITRE ATT&CK, with CI validation using sigma-cli and sample log events for testing.',
    milestones: [
      'Set up repository structure: rules/, tests/, docs/',
      'Write AWS rules: privilege escalation, S3 exfil, root activity, GuardDuty bypass attempt',
      'Write Linux rules: SSH brute force, crontab modification, SUID binary execution',
      'Write Windows rules: credential dumping, lateral movement, persistence',
      'Write container rules: privileged container spawn, container escape attempt',
      'Tag each rule to MITRE ATT&CK technique and tactic',
      'Add sample log events for each rule (positive and negative test cases)',
      'Set up GitHub Actions CI with sigma-cli validation on every PR',
      'Generate ATT&CK Navigator layer showing detection coverage',
      'Write technical blog post documenting the library',
    ],
    resumeTalkingPoints: 'Built detection library of 10+ production Sigma rules across 4 platforms (AWS, Linux, Windows, containers), ATT&CK-mapped with CI validation pipeline and sample log test cases.',
    skills: ['Sigma', 'MITRE ATT&CK', 'Detection Engineering', 'GitHub Actions', 'KQL', 'CloudTrail'],
  },
  {
    key: 'project_4_secrets_iam',
    title: 'Secrets & IAM Automation',
    description: 'Terraform-provisioned AWS environment with Secrets Manager, IAM Access Analyzer, and automated rotation script — demonstrates secure secrets lifecycle management and least-privilege IAM enforcement.',
    milestones: [
      'Write Terraform for AWS Secrets Manager with automatic rotation',
      'Write Terraform for IAM roles with permission boundaries',
      'Write Terraform for IAM Access Analyzer in all regions',
      'Write Python rotation Lambda function for RDS/API key rotation',
      'Write Boto3 script to export IAM Access Analyzer findings to CSV',
      'Write Boto3 script to detect and alert on IAM unused credentials',
      'Integrate Checkov scanning into Terraform pipeline',
      'Document least-privilege design decisions in README',
    ],
    resumeTalkingPoints: 'Implemented Terraform-based secrets lifecycle management with automated Secrets Manager rotation and IAM Access Analyzer integration for continuous least-privilege enforcement.',
    skills: ['Terraform', 'AWS Secrets Manager', 'AWS IAM', 'Boto3', 'Checkov', 'IaC Security'],
  },
  {
    key: 'project_5_vuln_assessment',
    title: 'Vulnerable App Security Assessment',
    description: 'Complete professional security assessment of OWASP Juice Shop combining automated SAST, DAST, SCA, manual testing, and a STRIDE threat model — documented as a professional pentest-style report.',
    milestones: [
      'Set up Juice Shop in Docker with a dedicated test environment',
      'Run SAST with Semgrep against Juice Shop source code',
      'Run SCA with OWASP Dependency-Check against npm dependencies',
      'Run DAST with OWASP ZAP in active scan mode',
      'Perform manual testing: OWASP Top 10 categories systematically',
      'Exploit and document: SQL injection, XSS, IDOR, auth bypass, JWT attacks',
      'Build STRIDE threat model for the application',
      'Write professional assessment report with executive summary and findings',
      'Produce CVSS scores for each finding with remediation guidance',
    ],
    resumeTalkingPoints: 'Conducted full-stack security assessment of OWASP Juice Shop using SAST + DAST + SCA + manual testing, produced professional report with 15+ findings including STRIDE threat model.',
    skills: ['AppSec', 'OWASP Top 10', 'DAST', 'SAST', 'Threat Modeling', 'Burp Suite', 'Manual Testing'],
  },
]

export const SKILL_CATEGORIES: SkillCategory[] = [
  { key: 'python_automation', title: 'Python for Security Automation', phase: 1 },
  { key: 'bash_linux', title: 'Bash and Linux', phase: 1 },
  { key: 'git_cicd', title: 'Git and CI/CD', phase: 1 },
  { key: 'github_actions', title: 'GitHub Actions / DevSecOps Pipeline', phase: 2 },
  { key: 'sast_sca', title: 'SAST / SCA / Secret Scanning', phase: 2 },
  { key: 'container_security', title: 'Container Security', phase: 2 },
  { key: 'aws_security', title: 'AWS Security Engineering', phase: 3 },
  { key: 'azure_security', title: 'Azure Security', phase: 3 },
  { key: 'iam_access', title: 'IAM and Access Design', phase: 3 },
  { key: 'iac_security', title: 'IaC Security (Terraform / Checkov)', phase: 3 },
  { key: 'detection_engineering', title: 'Detection Engineering (Sigma / KQL)', phase: 5 },
  { key: 'appsec', title: 'AppSec (OWASP / API Security)', phase: 4 },
  { key: 'threat_modeling', title: 'Threat Modeling', phase: 4 },
  { key: 'secrets_management', title: 'Secrets Management', phase: 3 },
  { key: 'vuln_management', title: 'Vulnerability Management Automation', phase: 2 },
  { key: 'ir_engineering', title: 'Incident Response Engineering', phase: 3 },
]

export const DEPTH_LABELS: Record<number, string> = {
  0: 'No Knowledge',
  1: 'Basic',
  2: 'Working',
  3: 'Strong',
  4: 'Interview-Ready',
}

export const PHASE_NAMES: Record<number, string> = {
  1: 'Engineering Foundations',
  2: 'DevSecOps Core',
  3: 'Cloud Security Engineering',
  4: 'Application Security Engineering',
  5: 'Detection Engineering',
  6: 'Portfolio + Capstone',
}

export function getAllTopicKeys(): string[] {
  return CURRICULUM.flatMap(phase => [
    ...phase.topics.map(t => t.key),
    ...phase.labs.map(l => l.key),
  ])
}

export function getTotalTopicsCount(): number {
  return CURRICULUM.reduce(
    (sum, phase) => sum + phase.topics.length + phase.labs.length,
    0
  )
}
