import type { InterviewQuestion } from '@/components/interview/interview-client'

export const INTERVIEW_QUESTIONS: Omit<InterviewQuestion, 'answered'>[] = [
  // ── Python / Scripting ──────────────────────────────────────────────────
  {
    id: 'py_1',
    question: 'Walk me through writing a Python script that parses a JSON log file and alerts on failed login attempts exceeding a threshold.',
    category: 'Python / Scripting',
    phase: 1,
    difficulty: 'junior',
    hint: 'Cover: file I/O, json.load(), iterating records, counter logic, threshold check, print/log output. Mention argparse for threshold as CLI arg.',
  },
  {
    id: 'py_2',
    question: 'How would you use Python\'s subprocess module to run a CLI security tool and capture its output for further processing?',
    category: 'Python / Scripting',
    phase: 1,
    difficulty: 'junior',
    hint: 'subprocess.run() with capture_output=True, check=True. Decode stdout. Handle CalledProcessError. Mention timeout parameter.',
  },
  {
    id: 'py_3',
    question: 'Describe how you would write a reusable Python module for interacting with a REST API, including authentication and error handling.',
    category: 'Python / Scripting',
    phase: 1,
    difficulty: 'mid',
    hint: 'requests.Session() for connection reuse, headers dict for auth token, retry logic with backoff, raise_for_status(), custom exception classes.',
  },

  // ── Linux / Bash ────────────────────────────────────────────────────────
  {
    id: 'linux_1',
    question: 'How do you use awk, sed, and grep together to extract failed SSH login IPs from /var/log/auth.log and count occurrences?',
    category: 'Linux / Bash',
    phase: 1,
    difficulty: 'junior',
    hint: 'grep "Failed password" | awk \'{print $11}\' | sort | uniq -c | sort -rn. Explain each pipe stage and what field numbers mean.',
  },
  {
    id: 'linux_2',
    question: 'Explain Linux file permissions, setuid, and how an attacker might abuse them for privilege escalation.',
    category: 'Linux / Bash',
    phase: 1,
    difficulty: 'mid',
    hint: 'rwxrwxrwx notation, octal. Setuid bit means executable runs as owner. find / -perm -4000. Classic examples: passwd, sudo misconfiguration.',
  },
  {
    id: 'linux_3',
    question: 'What is the difference between a hard link and a symlink, and what are the security implications of each?',
    category: 'Linux / Bash',
    phase: 1,
    difficulty: 'junior',
    hint: 'Hard link: same inode, persists if original deleted. Symlink: pointer, can dangle, can point outside chroot. TOCTOU attacks via symlinks.',
  },

  // ── Networking ──────────────────────────────────────────────────────────
  {
    id: 'net_1',
    question: 'Explain the TCP three-way handshake and how a SYN flood attack exploits it.',
    category: 'Networking',
    phase: 1,
    difficulty: 'junior',
    hint: 'SYN → SYN-ACK → ACK. Half-open connections exhaust server state. Mitigation: SYN cookies, rate limiting, firewall rules.',
  },
  {
    id: 'net_2',
    question: 'What happens at each layer of the OSI model during a DNS query, and where can attackers intercept or manipulate it?',
    category: 'Networking',
    phase: 1,
    difficulty: 'mid',
    hint: 'Application: DNS query. Transport: UDP 53. Network: IP routing. Attacks: DNS spoofing/cache poisoning (Layer 7), ARP poisoning (Layer 2). Mitigations: DNSSEC, DoH.',
  },
  {
    id: 'net_3',
    question: 'How does TLS 1.3 differ from TLS 1.2, and why do older TLS versions pose security risks?',
    category: 'Networking',
    phase: 1,
    difficulty: 'mid',
    hint: '1-RTT handshake, no RSA key exchange (forward secrecy only), removed weak ciphers. TLS 1.0/1.1: POODLE, BEAST, weak cipher suites.',
  },

  // ── Web Application Security ────────────────────────────────────────────
  {
    id: 'web_1',
    question: 'Explain SQL injection. How does a parameterized query prevent it, and what is a second-order SQL injection?',
    category: 'Web Security',
    phase: 2,
    difficulty: 'junior',
    hint: 'Attacker controls SQL via unsanitized input. Parameterized: DB treats input as data, not code. Second-order: stored input executed later in a different query.',
  },
  {
    id: 'web_2',
    question: 'What is the difference between stored, reflected, and DOM-based XSS? How does Content Security Policy help?',
    category: 'Web Security',
    phase: 2,
    difficulty: 'junior',
    hint: 'Stored: persisted in DB. Reflected: in URL response. DOM-based: client-side JS manipulation. CSP: allowlist of script sources, blocks inline unless nonce.',
  },
  {
    id: 'web_3',
    question: 'Walk through a CSRF attack scenario and explain how SameSite cookies and CSRF tokens each prevent it.',
    category: 'Web Security',
    phase: 2,
    difficulty: 'mid',
    hint: 'Attacker page makes cross-origin request with victim\'s cookies. CSRF token: server validates random value in request body. SameSite=Strict/Lax: browser won\'t send cookie cross-site.',
  },
  {
    id: 'web_4',
    question: 'How would you test a web application for IDOR vulnerabilities and what remediations would you recommend?',
    category: 'Web Security',
    phase: 2,
    difficulty: 'mid',
    hint: 'Change object IDs in requests (e.g., /api/user/123 → 124). Horizontal vs vertical privilege escalation. Fix: server-side authorization check on every request, not just URL.',
  },
  {
    id: 'web_5',
    question: 'Explain the OWASP Top 10 and walk through which three you consider most critical today and why.',
    category: 'Web Security',
    phase: 2,
    difficulty: 'junior',
    hint: 'Name the list, pick 3 and justify (e.g., A01 Broken Access Control #1 since 2021, A03 Injection, A02 Cryptographic Failures). Link to real breaches.',
  },

  // ── Cloud Security / AWS ────────────────────────────────────────────────
  {
    id: 'cloud_1',
    question: 'Explain the AWS Shared Responsibility Model. Who is responsible for what in an IaaS vs SaaS deployment?',
    category: 'Cloud Security',
    phase: 2,
    difficulty: 'junior',
    hint: 'AWS: hardware, hypervisor, physical. Customer: OS, patches, IAM, data, network config. SaaS shifts more responsibility to provider. "Security of the cloud" vs "in the cloud".',
  },
  {
    id: 'cloud_2',
    question: 'What is the principle of least privilege and how do you apply it to AWS IAM roles and policies?',
    category: 'Cloud Security',
    phase: 2,
    difficulty: 'junior',
    hint: 'Grant minimum permissions needed. IAM: specific actions (not *), specific resources (not *), conditions (MFA, IP, time). Use roles over users. Regularly review with IAM Access Analyzer.',
  },
  {
    id: 'cloud_3',
    question: 'How would you detect and respond to a compromised AWS access key that was accidentally pushed to GitHub?',
    category: 'Cloud Security',
    phase: 2,
    difficulty: 'mid',
    hint: 'Immediately: deactivate key in IAM. Then: CloudTrail → filter by AccessKeyId, identify actions taken. Check for new IAM users/roles, unusual regions, data exfil. Rotate all keys.',
  },
  {
    id: 'cloud_4',
    question: 'Describe how you would architect a zero-trust network model in AWS using VPC, security groups, and IAM.',
    category: 'Cloud Security',
    phase: 3,
    difficulty: 'senior',
    hint: 'No implicit trust. IAM: role-based, no long-term keys. VPC: private subnets, NACLs, security groups per resource. PrivateLink over public endpoints. mTLS between services. AWS Verified Access.',
  },

  // ── SIEM / Detection ────────────────────────────────────────────────────
  {
    id: 'siem_1',
    question: 'What is the difference between a SIEM and a SOAR platform, and how do they work together in a SOC?',
    category: 'SIEM / Detection',
    phase: 3,
    difficulty: 'junior',
    hint: 'SIEM: log aggregation, correlation, alerting (Splunk, Sentinel). SOAR: automated response playbooks (Cortex XSOAR, Sentinel Playbooks). SIEM detects → SOAR responds.',
  },
  {
    id: 'siem_2',
    question: 'Walk through writing a KQL query in Microsoft Sentinel to detect brute-force login attempts.',
    category: 'SIEM / Detection',
    phase: 3,
    difficulty: 'mid',
    hint: 'SigninLogs | where ResultType != 0 | summarize FailCount=count() by UserPrincipalName, IPAddress, bin(TimeGenerated, 1h) | where FailCount > 10. Explain each clause.',
  },
  {
    id: 'siem_3',
    question: 'What is the MITRE ATT&CK framework and how would you use it to map detections in a SIEM?',
    category: 'SIEM / Detection',
    phase: 3,
    difficulty: 'mid',
    hint: 'Tactics (high-level goals), Techniques (how), Sub-techniques. Use it to: identify coverage gaps, tag alerts with ATT&CK IDs, prioritize detection engineering, report to management.',
  },
  {
    id: 'siem_4',
    question: 'How do you tune a detection rule to reduce false positives without missing true positives?',
    category: 'SIEM / Detection',
    phase: 3,
    difficulty: 'mid',
    hint: 'Baseline normal behavior first. Add exclusions for known-good sources. Use thresholds, time windows, correlated conditions. Track FP/TP ratio. Review after every change.',
  },

  // ── CI/CD Security / DevSecOps ──────────────────────────────────────────
  {
    id: 'cicd_1',
    question: 'How would you integrate security scanning into a GitHub Actions CI/CD pipeline without slowing down deployments?',
    category: 'DevSecOps / CI-CD',
    phase: 3,
    difficulty: 'mid',
    hint: 'SAST on PR (Semgrep, CodeQL) — fast, runs in parallel. SCA (Dependabot/Snyk) on dependency changes. Secret scanning always on. DAST on staging, not every PR. Set severity thresholds to fail build.',
  },
  {
    id: 'cicd_2',
    question: 'What is a supply chain attack? Name a real example and explain how you would defend against it.',
    category: 'DevSecOps / CI-CD',
    phase: 3,
    difficulty: 'mid',
    hint: 'SolarWinds (build system compromise), Log4Shell (open-source dep), XZ Utils backdoor (maintainer compromise). Defenses: pin dependency versions, verify checksums/SBOMs, restrict CI/CD secrets, private registries.',
  },
  {
    id: 'cicd_3',
    question: 'Explain the concept of Infrastructure as Code (IaC) security scanning. What tools would you use and what do they detect?',
    category: 'DevSecOps / CI-CD',
    phase: 3,
    difficulty: 'mid',
    hint: 'Checkov, tfsec, KICS scan Terraform/CloudFormation for misconfigs: open security groups, public S3, unencrypted volumes, missing logging. Integrate into PR checks. Shift-left vs runtime scanning.',
  },

  // ── Containers / Kubernetes ──────────────────────────────────────────────
  {
    id: 'k8s_1',
    question: 'What are the main security risks of running containers as root, and how do you enforce non-root in Kubernetes?',
    category: 'Containers / K8s',
    phase: 4,
    difficulty: 'mid',
    hint: 'Root in container ≈ root on host if container escapes. Pod Security Standards: runAsNonRoot: true, runAsUser: 1000, readOnlyRootFilesystem. Admission controllers (OPA Gatekeeper).',
  },
  {
    id: 'k8s_2',
    question: 'How does Kubernetes RBAC work and how would you audit it for overly permissive roles?',
    category: 'Containers / K8s',
    phase: 4,
    difficulty: 'mid',
    hint: 'Subjects (users/SAs) bound to Roles/ClusterRoles via RoleBindings. Audit: kubectl auth can-i --list, rbac-lookup, check for wildcard verbs/resources, cluster-admin bindings. Least privilege principle.',
  },
  {
    id: 'k8s_3',
    question: 'Walk through your approach to securing a Docker image throughout its lifecycle from development to production.',
    category: 'Containers / K8s',
    phase: 4,
    difficulty: 'mid',
    hint: 'Dev: minimal base image (distroless/alpine), no secrets in layers. Build: Trivy scan in CI, sign with cosign. Registry: private, immutable tags. Runtime: read-only FS, drop capabilities, seccomp/AppArmor.',
  },

  // ── Threat Modeling ──────────────────────────────────────────────────────
  {
    id: 'threat_1',
    question: 'Walk me through a threat model for a web API that handles sensitive user data.',
    category: 'Threat Modeling',
    phase: 4,
    difficulty: 'mid',
    hint: 'Use STRIDE or PASTA. Draw data flow diagram. Identify: Spoofing (auth), Tampering (input validation), Repudiation (logging), Info Disclosure (encryption, error messages), DoS (rate limiting), EoP (authz checks).',
  },
  {
    id: 'threat_2',
    question: 'What is STRIDE and how do you apply it to find threats in a system design?',
    category: 'Threat Modeling',
    phase: 4,
    difficulty: 'junior',
    hint: 'Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege. For each component/data flow, ask which STRIDE categories apply. Map to controls.',
  },

  // ── Incident Response ────────────────────────────────────────────────────
  {
    id: 'ir_1',
    question: 'You receive an alert that a production server is beaconing to an unknown external IP every 60 seconds. Walk through your incident response steps.',
    category: 'Incident Response',
    phase: 5,
    difficulty: 'mid',
    hint: 'Detect & triage. Contain: isolate host from network. Identify: check process (netstat, lsof), parent process, cron jobs, persistence mechanisms. Eradicate. Recover. Post-incident review. Document everything.',
  },
  {
    id: 'ir_2',
    question: 'What is the difference between containment, eradication, and recovery in incident response, and in what order do you perform them?',
    category: 'Incident Response',
    phase: 5,
    difficulty: 'junior',
    hint: 'Containment: stop the bleeding (isolate). Eradication: remove the threat (malware, backdoor). Recovery: restore to known-good state. Never skip containment to rush to recovery.',
  },
  {
    id: 'ir_3',
    question: 'How would you perform digital forensics on a potentially compromised Linux system without altering evidence?',
    category: 'Incident Response',
    phase: 5,
    difficulty: 'senior',
    hint: 'Order of volatility: RAM first (LiME), then running processes, network connections, disk image (dd/FTK Imager, hash immediately). Mount read-only. Document chain of custody. Don\'t run tools on suspect system.',
  },

  // ── Security Architecture ────────────────────────────────────────────────
  {
    id: 'arch_1',
    question: 'What is defence in depth and how would you apply it to protect a web application?',
    category: 'Security Architecture',
    phase: 5,
    difficulty: 'junior',
    hint: 'Multiple overlapping controls: WAF, input validation, parameterized queries, encryption at rest/transit, least privilege, logging/monitoring, network segmentation. No single point of failure.',
  },
  {
    id: 'arch_2',
    question: 'How does zero trust differ from traditional perimeter-based security, and what are the core pillars of a zero-trust architecture?',
    category: 'Security Architecture',
    phase: 5,
    difficulty: 'mid',
    hint: 'Traditional: trust inside the perimeter. ZT: never trust, always verify. Pillars: identity (MFA, SSO), device health, least privilege access, microsegmentation, encryption everywhere, continuous verification.',
  },
  {
    id: 'arch_3',
    question: 'Design a secrets management strategy for a microservices application running on Kubernetes.',
    category: 'Security Architecture',
    phase: 5,
    difficulty: 'senior',
    hint: 'Never hardcode secrets. Options: HashiCorp Vault with K8s auth, AWS Secrets Manager with IRSA, Sealed Secrets, External Secrets Operator. Rotate secrets regularly. Audit access. No secrets in env vars (prefer mounted volumes).',
  },

  // ── Behavioural / Soft Skills ────────────────────────────────────────────
  {
    id: 'soft_1',
    question: 'Tell me about a time you found a security vulnerability in a system. How did you handle disclosure and remediation?',
    category: 'Behavioural',
    phase: 1,
    difficulty: 'junior',
    hint: 'STAR format: Situation, Task, Action, Result. Key points: responsible disclosure, working with the team, not just finding but fixing, follow-up to verify patched.',
  },
  {
    id: 'soft_2',
    question: 'How do you communicate a high-severity security risk to a non-technical stakeholder who is resistant to fixing it?',
    category: 'Behavioural',
    phase: 1,
    difficulty: 'mid',
    hint: 'Translate to business risk (data breach cost, compliance fines, reputational damage). Show likelihood × impact. Propose remediation options with trade-offs. Document the risk if they accept it.',
  },
  {
    id: 'soft_3',
    question: 'Describe how you stay current with the security threat landscape. What sources do you follow?',
    category: 'Behavioural',
    phase: 1,
    difficulty: 'junior',
    hint: 'Mention: CISA advisories, NVD/CVEs, Krebs on Security, threat intel feeds (STIX/TAXII), vendor advisories (Microsoft MSRC, AWS Security Bulletins), CTF competitions, security conferences (DEF CON, Black Hat talks on YouTube).',
  },
]
